version: "3"
services:
  my-service:
    image: node:14.15.5
    env_file: .env
    volumes:
      - .:/app
    working_dir: /app
    command: node --inspect=0.0.0.0:5858 bin/www
    ports:
      - 3000:3000
      - 5858:5858
